### ISSUE TITLE
“Major changes” / versioning policy / language consistency

### ISSUE THREAD

**Issue by khaeru** [sdmx-twg/sdmx-3_1_0#1]
The README of this repository has a heading “SDMX 3.1.0 Major Changes”, and the draft document for “Section 1” includes a heading “2.4 Major Changes from 3.0 to 3.1.0”. At the same time, section “2.3 Major changes from 2.1 to 3.0” of the same document includes:
> Versioning of Structural Metadata Artefacts
> - Adoption of the three-number semantic versioning standard for structural metadata artefacts (https://semver.org/)

This addition reveals that there was no clear versioning standard or policy for SDMX *per se*. **If** it were semantic versioning, the change from SDMX 3.0.0 to 3.1.0 would be a "minor" change, and the SemVer standard says:
> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> 1. MAJOR version when you make incompatible API changes
> 2. MINOR version when you add functionality in a backward compatible manner
> 3. PATCH version when you make backward compatible bug fixes

This would imply that all changes in 3.1.0, such as "Data Constraint: Reference reversed" should be implemented in a "backward compatible manner"; something that is not addressed in the updated text of the documents in this repo.

Conversely, if this is indeed a backwards-**in**compatible/“major” change, then SemVer would require that the version number be incremented "4.0.0".

So it seems clear that SemVer is not in use for SDMX itself. It would be good to have a clear statement of the meaning of the different parts of the SDMX version number, and when and how they will be incremented.

**Comment by agent96** [comment]
Thank you for your feedback.  The SDMX Standard does not strictly follow semantic versioning, to avoid confusion we have decided to revert to the 2-part versioning syntax for the release, i.e. SDMX v3.1

We will also document how to upgrade / downgrade Data Constraints between version 3.0 and 3.1 to allow automation when moving between versions.

**Comment by khaeru** [comment]
Thanks for this response! Now that I know this repo is being monitored, I can open a couple more issues.

I think the more general/over-arching point is still not addressed:

> This addition reveals that there was no clear versioning standard or policy for SDMX _per se_.

To be clear, I think it would be good to have such a positive statement saying what the versioning policy actually is—beyond the negative statement “it's not ‘strictly’ semantic versioning”.

For implementers, it is important to know:
- How often might "minor" (3.0 → 3.1) or "major" (3.0 → 4.0) revisions be made?
- What do these signify?
- How large would be the changes in each kind of update?

These determine how much work is needed to keep our implementations up to date with such changes.

**Comment by agent96** [comment]
SDMX versions are decided by the TWG and approved by the secretariat, there is not a defined methodology that I can share with you. However, if you are looking for a general principle I would say that a major version release like SDMX 3.0 touches upon multiple parts of the SDMX Information Model and may contain a number of breaking changes which makes it hard to move information from the 2.1 model to 3.0 and back again.  A minor release like SDMX 3.1 is limited in scope, in this case the changes focus on the Constraint model to support a specific use case.

**Comment by khaeru** [comment]
> a major version release like SDMX 3.0 touches upon multiple parts of the SDMX Information Model and may contain a number of breaking changes which makes it hard to move information from the 2.1 model to 3.0 and back again. A minor release like SDMX 3.1 is limited in scope, in this case the changes focus on the Constraint model to support a specific use case.

That sounds reasonable. It would be good to have this included in the actual standards document.

**Comment by agent96** [comment]
Thank you for your feedback.  Your comments have been noted.
